### ISSUE TITLE
ß alignment

### ISSUE THREAD

**Issue by aaronbell** [matsuba723/Aoboshi#4]
Generally the Latin letters all align with the baseline (or overshoots), but in the case of the ß, the right side is above the baseline. In reviewing the font, I can see that this kind of bounciness is present in other glyphs across the Japanese / Kana, but because the ß is the *only* Latin glyph that shows this personality, it looks out of place. It would be better to bring it into proper alignment.

**Comment by mintoming** [comment]
Fixed & updated. Please check @aaronbell ;)

**Comment by matsuba723** [comment]
Thanks :D
